version: "3.7"
  
volumes:
  nuoadmin-raft-1:
  nuoadmin-raft-2:
  hockey-arch-vol-1:
 
services:
 nuoadmin1:
   image: nuodb/nuodb-ce:latest
   environment:
     NUODB_DOMAIN_ENTRYPOINT: nuoadmin1
     NUOCMD_API_SERVER: http://nuoadmin1:8888
   hostname: nuoadmin1
   volumes:
     - nuoadmin-raft-1:/var/opt/nuodb
   command: ["nuoadmin", "--", "ssl=false"]
#  nuoadmin2:
#    image: nuodb/nuodb-ce:latest
#    environment:
#      NUODB_DOMAIN_ENTRYPOINT: nuoadmin1
#      NUOCMD_API_SERVER: http://nuoadmin2:8888
#    hostname: nuoadmin2
#    volumes:
#      - nuoadmin-raft-2:/var/opt/nuodb
#    command: ["nuoadmin", "--", "ssl=false"]
 sm:
   image: nuodb/nuodb-ce:latest
   hostname: sm
   environment:
     NUOCMD_API_SERVER: http://nuoadmin1:8888
   volumes:
     - hockey-arch-vol-1:/var/opt/nuodb
   depends_on:
   - nuoadmin1
   command: ["nuodocker", "start", "sm", "--db-name", "hockey", "--server-id", "nuoadmin1", "--dba-user", "dba", "--dba-password", "goalie", "--servers-ready-timeout", "15000"]
 te:
   image: nuodb/nuodb-ce:latest
   hostname: te
   environment:
     NUOCMD_API_SERVER: http://nuoadmin1:8888
   depends_on:
   - nuoadmin1
   - sm
   ports:
    - "8890:8890"
  #  deploy:
  #    replicas: 2
   command: ["nuodocker", "start", "te", "--db-name", "hockey", "--server-id", "nuoadmin1", "--servers-ready-timeout", "15000"]
