services:
  nuoadmin1:
    image: nuodb/nuodb-ce:latest
    container_name: nuoadmin1
    hostname: nuoadmin1
    environment:
      - "NUODB_DOMAIN_ENTRYPOINT=nuoadmin1"
    networks:
      - nuodb-net
    ports:
      - "8888:8888"
    volumes:
      - nuoadmin-raft-1:/var/opt/nuodb
    command: nuoadmin

  # test-sm-1:
  #   image: nuodb/nuodb-ce:latest
  #   container_name: test-sm-1
  #   hostname: test-sm-1
  #   networks:
  #     - nuodb-net
  #   volumes:
  #     - test-arch-vol-1:/var/opt/nuodb/archive
  #   depends_on:
  #     - nuoadmin1
  #   command: >
  #     nuodocker --api-server nuoadmin1:8888
  #     start sm --db-name test --server-id nuoadmin1
  #     --dba-user dba --dba-password goalie

  # test-te-1:
  #   image: nuodb/nuodb-ce:latest
  #   container_name: test-te-1
  #   hostname: test-te-1
  #   networks:
  #     - nuodb-net
  #   depends_on:
  #     - test-sm-1
  #   command: >
  #     nuodocker --api-server nuoadmin1:8888
  #     start te --db-name test
  #     --server-id nuoadmin1

networks:
  nuodb-net:
    driver: bridge

volumes:
  nuoadmin-raft-1:
    driver: local
  test-arch-vol-1:
    driver: local
