services:
  nuoadmin1:
    image: nuodb/nuodb-ce:latest
    environment:
      NUODB_DOMAIN_ENTRYPOINT: nuoadmin1
    hostname: nuoadmin1
    restart: unless-stopped
    command: ["nuoadmin"]
    ports:
      - "8888:8888"
    volumes:
      - ./tables.sql:/tmp/tables.sql
      - ./csv/genders.csv:/tmp/genders.csv
      - ./csv/authors.csv:/tmp/authors.csv
      - ./csv/documents_authors.csv:/tmp/documents_authors.csv
      - ./csv/documents.csv:/tmp/documents.csv
      - ./csv/geo_location.csv:/tmp/geo_location.csv
      - ./csv/vocabulary.csv:/tmp/vocabulary.csv
      - ./csv/words.csv:/tmp/words.csv
  sm:
    image: nuodb/nuodb-ce:latest
    hostname: sm
    restart: unless-stopped
    environment:
      NUOCMD_API_SERVER: nuoadmin1:8888
    depends_on:
    - nuoadmin1
    command: ["nuodocker", "start", "sm", "--db-name", "hockey", "--server-id", "nuoadmin1",
        "--dba-user", "dba", "--dba-password", "goalie",
        "--servers-ready-timeout", "60"]
  te:
    image: nuodb/nuodb-ce:latest
    hostname: te
    restart: unless-stopped
    environment:
      NUOCMD_API_SERVER: nuoadmin1:8888
    depends_on:
    - nuoadmin1
    - sm
    command: ["nuodocker", "start", "te", "--db-name", "hockey", "--server-id", "nuoadmin1",
          "--servers-ready-timeout", "60"]
